[tools]
node = '24.13.0'

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true

[env]
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.pnpm-install]
description = 'Installs dependencies with pnpm'
run = 'pnpm install'
sources = ['package.json', 'pnpm-lock.yaml', 'mise.toml']
outputs = ['node_modules/.pnpm/lock.yaml']

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'node --run dev'
depends = ['pnpm-install']

[tasks.build]
description = 'Build the app'
run = 'tsc'
depends = ['pnpm-install']

[tasks.start]
description = 'Start the app'
run = 'node --run start'
depends = ['build']

[tasks.deploy]
description = 'Deploy the commands'
run = 'node --run deploy'
depends = ['build']

[tasks.studio]
description = 'Open the Drizzle Studio'
run = 'pnpm drizzle-kit studio'
depends = ['pnpm-install']